### ISSUE TITLE
piping with trailing < source

### ISSUE THREAD

**Issue by Dierk** [kobo/groovyserv#10]
on the command shell (OS X Terminal) the following works
cat data.txt | groovyclient -e "println System.in.text"
but the following equivalent does not
groovyclient -e "println System.in.text" < data.txt

it's by no means a showstopper but since groovyserv makes command-line scripting with groovy so crispy, it would be good if supporting this scenario would be possible

**Comment by nobeans** [comment]
I've confirmed this but it seems alread be fixed.

```
$ cat data.txt
hello
foo
bar
this is end.

$ cat data.txt | groovyclient -e "println System.in.text"
hello
foo
bar
this is end.


$ groovyclient -e "println System.in.text" < data.txt
hello
foo
bar
this is end.


$ groovyclient -v
Groovy Version: 2.4.8 JVM: 1.8.0_111 Vendor: Oracle Corporation OS: Mac OS X
GroovyServ Version: Server: 1.1.0
GroovyServ Version: Client: 1.1.0
```
