### ISSUE TITLE
groovyserv exec format error on ubuntu 32 bit

### ISSUE THREAD

**Issue by corneil** [kobo/groovyserv#64]
I recently wanted to give groovyserv a try and use gvm install groovyserv
When I executed ~/.gvm/groovyserv/current/bin/groovyserver 
I received an error: cannot execute binary file: Exec format error
I then downloaded https://bitbucket.org/kobo/groovyserv-mirror/downloads/groovyserv-1.0.0-bin.zip
I extracted the zip file and executed bin/setup.sh which printed:
Setup completed successfully for linux_amd64
While my system is linux-i386

I checked setup.sh and it contains the following:
```bash
case `uname -m` in
    "x86_64" | "i686")
        arch=amd64
        ;;
    *)
        arch=386
        ;;
```

* i686 is the value of uname -m for 32 bit ubuntu not 64bit.
* x86_64 is the value for 64bit

**Comment by nobeans** [comment]
You're right! I've fixed it. Thank you for your feedback.
