### ISSUE TITLE
Groovy takes too long to start on Raspberry PI

### ISSUE THREAD

**Issue by BillKress** [kobo/groovyserv#69]
The server script always errors the first time you run it on the RPI.

Allowing the timeout to be a parameter wouldn't be a bad idea--but since hitting the timeout is an exception scenario anyway it would probably be fine to set the default to 20+ seconds.

Even if it is added as a parameter, I suggest bumping the default up by 5 or so just so it works for everyone by default (Anyone who has common failures on a fast machine could set it to a lower number, but I can't imagine a scenario where it fails so often that this is important.)

**Comment by nobeans** [comment]
Fix at 1.1.0.

```
$ groovyclient -Ch
usage: groovyclient -C[option for groovyclient] [args/options for groovy]
options:
...
  -Ct,-Ctimeout <second>           specify a timeout waiting for starting up a
                                   server process (default: 20 sec)
...

$ groovyserver -h
usage: groovyserver [options]
options:
...
  -t,--timeout <second>            specify a timeout waiting for starting up a server process (default: 20 sec)
...
```
