### ISSUE TITLE
Suggestion to solve the "cd" problem

### ISSUE THREAD

**Issue by BillKress** [kobo/groovyserv#71]
If groovyclient had a command line switch that essentially said "don't CD", you could have any number of scripts run concurrently as long as only one of them did not supply the "Don't CD" switch.  As long as that switch was bound to the .groovy script (in the #! line, for instance), we could identify scripts that required CD and those that did not and just tag them appropriately.

The switch is good but Windows does not have the shebang line, plus sometimes we might want to have a long-running script that knows what directory it was launched form.  For this we could use an annotation to identify scripts that don't require CD and this annotation could actually annotate a variable to contain the original path.  Something like:

  import org.groovyserv.whatever.NoCD;
  
  @NoCD
  def startLocation
  
  println startLocation

The existence of the NoCD annotation would cause groovyserv to skip the change directory--but startLocation could be used to access file objects relative to the directory the groovyclient was executed in if necessary.

Neither of these options would change existing behavior, it's just a way to ensure that a script will never fail to run and allow scripts to run for a long period of time without blocking others.

It would still be necessary to track if the server is currently running in a different directory just the same as it is now, it's just that some scripts could avoid the check.

**Comment by nobeans** [comment]
It seems nice idea.

To support "no cd" mode with command option of groovyclient is easy, so I tried it:  bca2fcc.
You can use the feature like this:
```
groovyclient -Ckeep-server-cwd -e "println(new File('.').absolutePath)"
```

But both to using annotation and to refer the client CWD from user script aren't easy very much.

At least, now you can run scripts concurrently easier than before by bca2fcc. How about this fix?
