### ISSUE TITLE
Broken installation on windows 7 since 1.1.0 (working in 1.0.0)

### ISSUE THREAD

**Issue by cebbec** [kobo/groovyserv#74]
From a windows command line :

`C:\groovyserv-1.1.0\bin>setup
Setup completed successfully for windows_386

C:\groovyserv-1.1.0\bin>groovyserver -r
panic: runtime error: index out of range

goroutine 1 [running]:
panic(0x533ee0, 0x10a20008)
        /opt/homebrew/Cellar/go/1.6.3/libexec/src/runtime/panic.go:481 +0x326
path/filepath.walkLinks(0x10a04420, 0x18, 0x10a63e74, 0x0, 0x0, 0x0, 0x0)
        /opt/homebrew/Cellar/go/1.6.3/libexec/src/path/filepath/symlink.go:84 +0x53e
path/filepath.walkLinks(0x10a04420, 0x19, 0x10a63e74, 0x0, 0x0, 0x0, 0x0)
        /opt/homebrew/Cellar/go/1.6.3/libexec/src/path/filepath/symlink.go:68 +0x1c9
path/filepath.walkLinks(0x10a04420, 0x23, 0x10a63e74, 0x0, 0x0, 0x0, 0x0)
        /opt/homebrew/Cellar/go/1.6.3/libexec/src/path/filepath/symlink.go:73 +0x275
path/filepath.walkSymlinks(0x10a04420, 0x23, 0x0, 0x0, 0x0, 0x0)
        /opt/homebrew/Cellar/go/1.6.3/libexec/src/path/filepath/symlink.go:98 +0x7c
path/filepath.evalSymlinks(0x10a04420, 0x23, 0x0, 0x0, 0x0, 0x0)
        /opt/homebrew/Cellar/go/1.6.3/libexec/src/path/filepath/symlink_windows.go:50 +0x41
path/filepath.EvalSymlinks(0x10a04420, 0x23, 0x0, 0x0, 0x0, 0x0)
        /opt/homebrew/Cellar/go/1.6.3/libexec/src/path/filepath/path.go:227 +0x3d
_/Users/ynak/Developer/workspace/groovyserv/src/main/go/common.ExpandPath(0x10a04420, 0x23, 0x0, 0x0)
        /Users/ynak/Developer/workspace/groovyserv/src/main/go/common/io.go:54 +0x37
_/Users/ynak/Developer/workspace/groovyserv/src/main/go/server.groovyServWorkDir(0x0, 0x0)
        /Users/ynak/Developer/workspace/groovyserv/src/main/go/server/util.go:27 +0xf5
_/Users/ynak/Developer/workspace/groovyserv/src/main/go/server.init()
        /Users/ynak/Developer/workspace/groovyserv/src/main/go/server/server.go:39 +0xcf
main.init()
        /Users/ynak/Developer/workspace/groovyserv/src/main/go/cmd/groovyserver/groovyserver.go:167 +0x43
`

**Comment by nobeans** [comment]
I'm sorry for too late response because the notification was off...

Please some additional information.

- Windows 7 [32bit, 64bit]?
- Console [DOS, PowerShell, Cygwin or others]?
- Installation [binary ZIP(from where?), SDKman, self-build from source code]

**Comment by cebbec** [comment]
I have migrated to windows 10.
I was on windows 7 64bit.
I was using Console DOS.
I installed with the binary zip (from https://kobo.github.io/groovyserv/download.html).
May we can close this issue.
