### ISSUE TITLE
Groovyserv broken on macOS 10.13 High Sierra

### ISSUE THREAD

**Issue by fvanwesterop** [kobo/groovyserv#78]
I upgraded my mac to High Sierra by wiping the disk and installing from scratch a few days ago. Groovy and Java are working fine (both installed with SDKMan). Now I installed groovyserv again too, but it seems to be broken, perhaps it can't deal with macOS 10.13 yet?.

`## Software versions:`
macOS 10.13 (17A365), Kernel Version: Darwin 17.0.0
Groovy 2.4.12
Java 1.8.0_144 Vendor: Azul Systems, Inc.
Groovyserv 1.1.0
Homebrew 1.3.4 (git revision efc2; last commit 2017-10-07)
SDKMAN 5.5.11+256

`## WHEN installing with SDKMan:`

➜  ~ sdk i groovyserv 1.1.0
Downloading: groovyserv 1.1.0

In progress...

######################################################################## 100.0%

Installing: groovyserv 1.1.0
Done installing!

Setting groovyserv 1.1.0 as default.

`## THEN running groovyclient fails:`

➜  ~ groovyclient -v
Setup completed successfully for darwin_amd64.
It's required only just after installation. Please run the same command once again.
➜  ~ groovyclient -v
[1]    74426 segmentation fault  groovyclient -v

`WHEN installing with Homebrew:`

➜  ~ brew install groovyserv
Updating Homebrew...®
==> Auto-updated Homebrew!
Updated 1 tap (homebrew/core).
No changes to formulae.

==> Installing dependencies for groovyserv: groovy
==> Installing groovyserv dependency: groovy
==> Downloading https://dl.bintray.com/groovy/maven/apache-groovy-binary-2.4.12.zip
Already downloaded: /Users/frank/Library/Caches/Homebrew/groovy-2.4.12.zip
==> Caveats
You should set GROOVY_HOME:
  export GROOVY_HOME=/usr/local/opt/groovy/libexec
==> Summary
🍺  /usr/local/Cellar/groovy/2.4.12: 65 files, 27.6MB, built in 3 seconds
==> Installing groovyserv
==> Downloading https://homebrew.bintray.com/bottles/groovyserv-1.1.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/frank/Library/Caches/Homebrew/groovyserv-1.1.0.high_sierra.bottle.tar.gz
==> Pouring groovyserv-1.1.0.high_sierra.bottle.tar.gz
🍺  /usr/local/Cellar/groovyserv/1.1.0: 11 files, 5.7MB

`## AND remove brew install of Groovy 2.14.12 since it's already installed with SDKMan`

➜  ~ brew uninstall --ignore-dependencies groovy
Uninstalling /usr/local/Cellar/groovy/2.4.12... (65 files, 27.6MB)
➜  ~ groovy -version
Groovy Version: 2.4.12 JVM: 1.8.0_144 Vendor: Azul Systems, Inc. OS: Mac OS X

`## THEN running groovyclient fails:`

➜  ~ groovyclient -v
Java home directory: /Users/frank/.sdkman/candidates/java/current
Groovy home directory: /Users/frank/.sdkman/candidates/groovy/current
Groovy command path: /Users/frank/.sdkman/candidates/groovy/current/bin/groovy (found at GROOVY_HOME)
GroovyServ home directory: /usr/local/Cellar/groovyserv/1.1.0/libexec
GroovyServ work directory:
Original classpath: (none)
GroovyServ default classpath: /usr/local/Cellar/groovyserv/1.1.0/libexec/lib/*
Starting server........................................................................................................
ERROR: timed out while waiting for server startup`

**Comment by fvanwesterop** [comment]
Noticed the following when running groovyserv with the --debug switch:

`(...) GroovyServ default classpath: /usr/local/Cellar/groovyserv/1.1.0/libexec/lib/*
2017/10/07 22:36:58.838375 server.go:321: startInBackground: command: &exec.Cmd{Path:"/Users/frank/.sdkman/candidates/groovy/current/bin/groovy", Args:[]string{"/Users frank/.sdkman/candidates/groovy/current/bin/groovy", "-e", "groovyx.groovyserv.GroovyServer.main(args)", (...)`

And it finishes with:

`(...) Starting server......Caught: groovy.lang.MissingPropertyException: No such property: groovyx for class: script_from_command_line
groovy.lang.MissingPropertyException: No such property: groovyx for class: script_from_command_line
	at script_from_command_line.run(script_from_command_line:1)`

So that property 'groovyx.groovyserv.GroovyServer.main(args)' seems to fall apart when it is interpreted.

**Comment by nobeans** [comment]
Sorry for my late response.

It seems there is no compatibility for Go binary between Sierra and High-Sierra...
The binary you build by yourself on High-Sierra can work well. Could you build from source and use it?

**Comment by rubengomezmrf** [comment]
I'm having the same issue, so will we have to wait until brew updates the the library?

**Comment by oliverfernandez** [comment]
@nobeans What's needed to fix this? Can I contribute somehow?

**Comment by nobeans** [comment]
Hi @oliverfernandez and all,

Sorry for too much late, but now finally v1.2.0 has just released to SDKman! Please try it!

**Comment by fvanwesterop** [comment]
Great! Indeed, it took a while but I can confirm version 1.2.0 does work on macOS 10.3.3 (High Siera). Thanks!
