### ISSUE TITLE
Make groovyserv available for Java, Kotlin, Scala..?

### ISSUE THREAD

**Issue by wordlessly** [kobo/groovyserv#85]
This is more of a feature request. I would love to use this technology for executing my Java programs.

If you can run Groovy there is technically no reason why you couldn't run Java on a "hot" JVM, surely, isn't it?

**Comment by nobeans** [comment]
Yes, you're right. You can use GroovyServ for other JVM language if it has appropriate entry point.

https://kobo.github.io/groovyserv/faq.html#is-groovyserv-dedicated-for-groovy
